---
title: "Home Range Test"
author: "Mario"
date: "06/11/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(sf)
library(rgdal)
library(maptools)
library(readr)
library(magrittr)
library(dplyr)
library(adehabitatHR)
library(dplyr)
library(sp)
```
```{r}
###HR for 2016 lizards
HR <- read.csv("Liz_shape.csv")
HR <- HR %>% filter(status > 0) %>% filter(year == 2016) %>% filter(lizard != "aa")
HR$lizard <- as.factor(HR$lizard)

lizlist <- HR %>% group_by(lizard) %>% summarize(n = n()) %>% arrange(n) %>% filter(n>5)%>% dplyr::select(lizard) %>% extract2(1)%>%as.character()
HR <- HR %>% filter(lizard %in% lizlist) %>% droplevels()

par(mar=c(1, 1, 1, 1)) ###This fixes everything!!!

prj <- "+init=epsg:2679"
CRS("+init=epsg:2679")
spdf <- SpatialPointsDataFrame(coordinates(cbind(HR$x_utm, HR$y_utm)), 
                               data = HR, proj4string = CRS(prj))

cp <- mcp(spdf[,1], unout = c("ha"))
as.data.frame(cp)
plot(cp)
plot(spdf, col=as.data.frame(spdf[,1], add =TRUE))
cuicui <- mcp.area(spdf[,1], unout = c("ha"))

cuicui <- data.frame(t(cuicui)) #Need to flip the dataframe
#write.csv(cuicui, file = "HR2016.csv")
```
```{r}
###HR for 2017
HR2 <- read.csv("Liz_shape.csv")
HR2 <- HR2 %>% filter(status > 0) %>% filter(year == 2017)
HR2$lizard <- as.factor(HR2$lizard)

lizlist2 <- HR2 %>% group_by(lizard) %>% summarize(n = n()) %>% arrange(n) %>% filter(n>5)%>% dplyr::select(lizard) %>% extract2(1)%>%as.character()
HR2 <- HR2 %>% filter(lizard %in% lizlist2) %>% droplevels()

par(mar=c(1, 1, 1, 1)) ###This fixes everything!!!

prj <- "+init=epsg:2679"
CRS("+init=epsg:2679")
spdf2 <- SpatialPointsDataFrame(coordinates(cbind(HR2$x_utm, HR2$y_utm)), 
                               data = HR2, proj4string = CRS(prj))

cp2 <- mcp(spdf2[,1], unout = c("ha"))
as.data.frame(cp2)
plot(cp2)
plot(spdf2, col=as.data.frame(spdf2[,1], add =TRUE))
cuicui2 <- mcp.area(spdf2[,1], unout = c("ha"))

cuicui2 <- data.frame(t(cuicui2)) #flips the dataframe
#write.csv(cuicui2, file = "HR2017.csv")
```
```{r}
###HR for 2018
HR3 <- read.csv("Liz_shape.csv")
HR3 <- HR3 %>% filter(status > 0) %>% filter(year == 2018)
HR3$lizard <- as.factor(HR3$lizard)

lizlist3 <- HR3 %>% group_by(lizard) %>% summarize(n = n()) %>% arrange(n) %>% filter(n>5)%>% dplyr::select(lizard) %>% extract2(1)%>%as.character()
HR3 <- HR3 %>% filter(lizard %in% lizlist3) %>% droplevels()

par(mar=c(1, 1, 1, 1)) ###This fixes everything!!!

prj <- "+init=epsg:2679"
CRS("+init=epsg:2679")
spdf3 <- SpatialPointsDataFrame(coordinates(cbind(HR3$x_utm, HR3$y_utm)), 
                               data = HR3, proj4string = CRS(prj))

cp3 <- mcp(spdf3[,1], unout = c("ha"))
as.data.frame(cp3)
plot(cp3)
plot(spdf3, col=as.data.frame(spdf3[,1], add =TRUE))
cuicui3 <- mcp.area(spdf3[,1], unout = c("ha"))

cuicui3 <- data.frame(t(cuicui3)) #flips the dataframe
#write.csv(cuicui3, file = "HR2018.csv")
```

```{r}
###Tidy Up data
tidy_20m <- read.csv("tidy_20m.csv")%>%
  distinct(uniID, .keep_all = TRUE)
HR_final <- read.csv("HR_FINAL.csv")
tidy_20mdf <- tidy_20m[-1]
names(tidy_20mdf)[5] <- "lizard"


Liz_2016 <- read_csv("2016_lizards.csv")
Liz_2017 <- read_csv("2017_lizards.csv")
Liz_2018 <- read_csv("2018_lizards.csv")

Liz_2016_2017 <- merge(Liz_2016, Liz_2017, all = TRUE)
Liz_sex <- merge(Liz_2016_2017, Liz_2018, all = TRUE)

#write.csv(Liz_sex, file = "Liz_sex.csv")

#Set up Density data so we can merge with Lizard sex data
data_sex <- tidy_20m %>%
  dplyr::select(rep, status, lizard.x, year, ground, mesohabitat, Aspect.x, Slope.x, Elev.x, KDF.x, Shrub_Cov.x, NDVI.x, Solar.x, aspect.cat, twenty_meter)
data_sex <- data_sex[data_sex$twenty_meter <90,]
data_sex$year <-  as.character(data_sex$year)
names(data_sex)[3] <- "lizard"

#Join Lizard Sex with Telemetry data by lizard column
new_data <- left_join(data_sex, Liz_sex, by = "lizard")
names(new_data)[19] <- "sex"

###Join HR data with Lizard data
Data_HR <- left_join(new_data, HR_final, by = "lizard")
Data_HR <- Data_HR %>% filter(sex != "uk")

#write.csv(Data_HR, file = "Lizard Home Range.csv")

###Summarize data with X95 HR
summary <- Data_HR %>%
  group_by(year, sex, X95) %>%
  summarise()
summary <- summary %>%
  na.omit()

male_2016 <- summary %>% filter(sex != "f") %>%
  filter(year == "2016")
male_2016$st_error <- sd(male_2016$X95)/sqrt(length(male_2016$X95))

male_2017 <- summary %>% filter(sex != "f") %>%
  filter(year == "2017")
male_2017$st_error <- sd(male_2017$X95)/sqrt(length(male_2017$X95))

male_2018 <- summary %>% filter(sex != "f") %>%
  filter(year == "2018")
male_2018$st_error <- sd(male_2018$X95)/sqrt(length(male_2018$X95))

female_2016 <- summary %>% filter(sex != "m") %>%
  filter(year == "2016")
female_2016$st_error <- sd(female_2016$X95)/sqrt(length(female_2016$X95))

female_2017 <- summary %>% filter(sex != "m") %>%
  filter(year == "2017")
female_2017$st_error <- sd(female_2017$X95)/sqrt(length(female_2017$X95))

female_2018 <- summary %>% filter(sex != "m") %>%
  filter(year == "2018")
female_2018$st_error <- sd(female_2018$X95)/sqrt(length(female_2018$X95))

all_male <- rbind(male_2016, male_2017)
all_male <- rbind(all_male, male_2018)
all_female <- rbind(female_2016, female_2017)
all_female <- rbind(all_female, female_2018)
final_summary <- rbind(all_male, all_female)


final_summary <- final_summary %>%
  group_by(year, sex, st_error) %>%
  summarise(hr = mean(X95))


#write.csv(final_summary, file = "HR_Summary.csv")
```
```{r}
summary_liz <- Data_HR %>%
  group_by(lizard, year, sex, mass, SVL_mm, tail, tail_mm, X95) %>%
  summarise()
summary_liz <- summary_liz %>%
  na.omit()
names(summary_liz)[4] <- "HR"
#write.csv(summary_liz, file = "Lizard HR Summary")
```

```{r}
###with 100% MCP
summary <- Data_HR %>%
  group_by(year, sex, X100) %>%
  summarise()
summary <- summary %>%
  na.omit()

Liz_Summary <- Data_HR %>%
  group_by(lizard, year, sex, X100)%>%
  summarise() %>% na.omit()

write.csv(Liz_Summary, file = "Lizard_Summary.csv")

male_2016 <- summary %>% filter(sex != "f") %>%
  filter(year == "2016")
male_2016$st_error <- sd(male_2016$X100)/sqrt(length(male_2016$X100))

male_2017 <- summary %>% filter(sex != "f") %>%
  filter(year == "2017")
male_2017$st_error <- sd(male_2017$X100)/sqrt(length(male_2017$X100))

male_2018 <- summary %>% filter(sex != "f") %>%
  filter(year == "2018")
male_2018$st_error <- sd(male_2018$X100)/sqrt(length(male_2018$X100))

female_2016 <- summary %>% filter(sex != "m") %>%
  filter(year == "2016")
female_2016$st_error <- sd(female_2016$X100)/sqrt(length(female_2016$X100))

female_2017 <- summary %>% filter(sex != "m") %>%
  filter(year == "2017")
female_2017$st_error <- sd(female_2017$X100)/sqrt(length(female_2017$X100))

female_2018 <- summary %>% filter(sex != "m") %>%
  filter(year == "2018")
female_2018$st_error <- sd(female_2018$X100)/sqrt(length(female_2018$X100))

all_male <- rbind(male_2016, male_2017)
all_male <- rbind(all_male, male_2018)
all_female <- rbind(female_2016, female_2017)
all_female <- rbind(all_female, female_2018)
final_summary <- rbind(all_male, all_female)


final_summary <- final_summary %>%
  group_by(year, sex, st_error) %>%
  summarise(hr = mean(X100))

write.csv(final_summary, file ="HR_summary.csv")

library(emmeans)
m <- glm(X100~sex * year, family = gaussian, summary)
anova(m, test = "Chisq")
e <- emmeans(m, pairwise~sex|year)
e
```



```{r}
###Try with older CRS projection
###2016 Projections
track.pop <-HR
track.pop <- track.pop %>% filter(lizard != "x") #were not 5 relocations for x
coordinates(track.pop) <- ~long+lat
proj4string(track.pop) <- CRS("+proj=longlat") #assign projection and coordinate reference system
track.pop <- spTransform(track.pop, CRS("+proj=utm +zone=10")) #transform

par(mar=c(1, 1, 1, 1)) ###This fixes everything!!!

cp4 <- mcp(track.pop[,1], unout = c("ha"))
as.data.frame(cp4)
plot(cp4)
plot(track.pop, col=as.data.frame(track.pop[,1], add =TRUE))
cuicui4 <- mcp.area(track.pop[,1], unout = c("ha"))

cuicui4 <- data.frame(t(cuicui4)) #Need to flip the dataframe

#write.csv(cuicui4, file = "HR2016CRS.csv")

###2017 Projections
###HR for 2017
track.pop2 <-HR2
track.pop2 <- track.pop2 %>% filter(lizard != "x") #were not 5 relocations for x
coordinates(track.pop2) <- ~long+lat
proj4string(track.pop2) <- CRS("+proj=longlat") #assign projection and coordinate reference system
track.pop2 <- spTransform(track.pop2, CRS("+proj=utm +zone=10")) #transform

par(mar=c(1, 1, 1, 1)) ###This fixes everything!!!


cp5 <- mcp(track.pop2[,1], unout = c("ha"))
as.data.frame(cp5)
plot(cp5)
plot(track.pop2, col=as.data.frame(track.pop2[,1], add =TRUE))
cuicui5 <- mcp.area(track.pop2[,1], unout = c("ha"))

cuicui5 <- data.frame(t(cuicui5)) #Need to flip the dataframe

#write.csv(cuicui5, file = "HR2017CRS.csv")
###2018
track.pop3 <-HR3
track.pop3 <- track.pop3 %>% filter(lizard != "x") #were not 5 relocations for x
coordinates(track.pop3) <- ~long+lat
proj4string(track.pop3) <- CRS("+proj=longlat") #assign projection and coordinate reference system
track.pop3 <- spTransform(track.pop3, CRS("+proj=utm +zone=10")) #transform

par(mar=c(1, 1, 1, 1)) ###This fixes everything!!!


cp6 <- mcp(track.pop3[,1], unout = c("ha"))
as.data.frame(cp6)
plot(cp6)
plot(track.pop3, col=as.data.frame(track.pop3[,1], add =TRUE))
cuicui6 <- mcp.area(track.pop3[,1], unout = c("ha"))

cuicui6 <- data.frame(t(cuicui6)) #Need to flip the dataframe

#write.csv(cuicui6, file = "HR2018CRS.csv")
```

```{r}
###Set up with other CRS system

HR_final_CRS <- read.csv("HRS_ALL_CRS.csv")

Data_HR2 <- left_join(new_data, HR_final_CRS, by = "lizard")
Data_HR2 <- Data_HR %>% filter(sex != "uk")

#write.csv(Data_HR, file = "Lizard Home Range.csv")

###Summarize data with X95 HR
summary2 <- Data_HR %>%
  group_by(year, sex, X100) %>%
  summarise()
summary2 <- summary2 %>%
  na.omit()


male_2016 <- summary2 %>% filter(sex != "f") %>%
  filter(year == "2016")
male_2016$st_error <- sd(male_2016$X100)/sqrt(length(male_2016$X100))

male_2017 <- summary2 %>% filter(sex != "f") %>%
  filter(year == "2017")
male_2017$st_error <- sd(male_2017$X100)/sqrt(length(male_2017$X100))

male_2018 <- summary2 %>% filter(sex != "f") %>%
  filter(year == "2018")
male_2018$st_error <- sd(male_2018$X100)/sqrt(length(male_2018$X100))

female_2016 <- summary2 %>% filter(sex != "m") %>%
  filter(year == "2016")
female_2016$st_error <- sd(female_2016$X100)/sqrt(length(female_2016$X100))

female_2017 <- summary2 %>% filter(sex != "m") %>%
  filter(year == "2017")
female_2017$st_error <- sd(female_2017$X100)/sqrt(length(female_2017$X100))

female_2018 <- summary2 %>% filter(sex != "m") %>%
  filter(year == "2018")
female_2018$st_error <- sd(female_2018$X100)/sqrt(length(female_2018$X100))

all_male <- rbind(male_2016, male_2017)
all_male <- rbind(all_male, male_2018)
all_female <- rbind(female_2016, female_2017)
all_female <- rbind(all_female, female_2018)
final_summary2 <- rbind(all_male, all_female)


final_summary2 <- final_summary2 %>%
  group_by(year, sex, st_error) %>%
  summarise(hr = mean(X100))

m2 <- glm(X100~sex + year, family = gaussian, summary2)
anova(m2, test = "Chisq")
e2 <- emmeans(m, pairwise~sex|year)
e2

###Summary output provides the same data as the other one i ran so values are the same!

```


###Note: HR is in hectars


